# Generated by Django 3.0 on 2019-12-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('test', models.CharField(max_length=100)),
                ('background', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=400)),
                ('variants', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('background', models.ImageField(null=True, upload_to='')),
                ('answers', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('done', 'test is answered'), ('running', 'test is running now')], max_length=100)),
                ('statistics', models.CharField(max_length=400)),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Test')),
            ],
        ),
    ]
