# Generated by Django 3.0 on 2020-01-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_session_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
