# Generated by Django 3.0 on 2020-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200105_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='id',
        ),
        migrations.AlterField(
            model_name='session',
            name='test',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
