# Generated by Django 3.0 on 2020-01-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200105_1845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
    ]
