# Generated by Django 3.0 on 2020-01-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20200105_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='current',
            field=models.IntegerField(),
        ),
    ]
